# Generated by Django 5.2 on 2025-04-15 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='movies',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_names', to='app1.guest'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies_names', to='app1.movie'),
        ),
    ]
